"""The storage layer's contracts: what persistence owes its consumers.

Three protocols, one per storage concern.  Consumers (engine, ranker,
feedback loop) code against these and never see an implementation; the
factory is the only place that picks concrete stores.  Discipline
rules: the contracts are dependency-free plain interfaces, and
implementations live in the sqlite/ package (Postgres or Redis would
become sibling packages).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from crawlme.schemas import Candidate, Page, RankDecision


class CrawlDb(Protocol):
    """Contract for one crawl run's persisted state: SQLite today, Postgres tomorrow."""

    @property
    def db_path(self) -> str: ...

    async def start(self) -> None: ...
    async def close(self) -> None: ...

    def attach_log_file(self) -> None: ...

    def raw_html_path(self, url_key: str, fetch_id: str) -> str: ...
    def save_raw_html(self, url_key: str, fetch_id: str, content: bytes) -> str: ...

    def save_goal(self, goal_json: dict[str, Any]) -> None: ...
    def save_task(self, task_json: dict[str, Any]) -> None: ...
    def save_error(self, error_json: dict[str, Any]) -> None: ...
    def save_page(self, page: Page) -> None: ...
    def save_candidate(self, candidate: Candidate) -> None: ...
    def save_rank_decision(self, rd: RankDecision) -> None: ...
    def save_analysis(self, analysis_json: dict[str, Any]) -> None: ...
    def save_snapshot(self, snapshot_json: dict[str, Any]) -> None: ...
    def save_event(self, event_json: dict[str, Any]) -> None: ...

    async def get_snapshot(self, snapshot_id: str) -> dict[str, Any] | None: ...


class EmbeddingCache(Protocol):
    """Contract for persistent vector storage."""

    async def get_vectors(self, content_hashes: list[str]) -> dict[str, list[float]]: ...

    async def put_vectors(self, entries: list[tuple[str, list[float]]], model: str) -> None: ...

    async def close(self) -> None: ...


class DomainPrior(Protocol):
    """Contract for cross-task per-domain reputation storage."""

    def record(self, reg_domain: str, *, relevant: bool, relevance_score: float) -> None: ...

    async def load_all(self) -> dict[str, dict[str, float]]: ...

    async def close(self) -> None: ...
