"""The storage layer's contracts: what persistence owes its consumers.

Three protocols, one per storage concern.  Consumers (engine, ranker,
feedback loop) code against these and never see an implementation; the
factory is the only place that picks concrete stores.  Discipline
rules: the contracts are dependency-free plain interfaces, and
implementations live in the sqlite/ package (Postgres or Redis would
become sibling packages).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from crawlme.schemas import Candidate, Page, RankDecision


class CrawlDb(Protocol):
    """Contract for one crawl run's persisted state: SQLite today, Postgres tomorrow."""

    @property
    def db_path(self) -> str: ...

    async def start(self) -> None: ...
    async def close(self) -> None: ...

    def attach_log_file(self) -> None: ...

    def raw_html_path(self, url_key: str, fetch_id: str) -> str: ...
    def save_raw_html(self, url_key: str, fetch_id: str, content: bytes) -> str: ...
    def payload_path(self, url_key: str, fetch_id: str, index: int) -> str: ...
    def save_payload(self, url_key: str, fetch_id: str, index: int, content: bytes) -> str: ...

    def save_goal(self, goal_json: dict[str, Any]) -> None: ...
    def save_task(self, task_json: dict[str, Any]) -> None: ...
    def save_error(self, error_json: dict[str, Any]) -> None: ...
    def save_page(self, page: Page) -> None: ...
    def save_link(self, candidate: Candidate) -> None: ...
    def save_rank_decision(self, rd: RankDecision) -> None: ...
    def save_analysis(self, analysis_json: dict[str, Any]) -> None: ...
    def save_snapshot(self, snapshot_json: dict[str, Any]) -> None: ...
    def save_event(self, event_json: dict[str, Any]) -> None: ...

    async def get_goal(self, goal_id: str) -> dict[str, Any] | None: ...
    async def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    async def get_snapshot(self, snapshot_id: str) -> dict[str, Any] | None: ...
    # replay / inspect readers ---------------------------------------
    async def list_pages(self) -> list[dict[str, Any]]: ...
    async def has_analysis(self, url_key: str, goal_id: str, prompt_version: str, model: str = "") -> bool: ...
    async def list_goals(self) -> list[dict[str, Any]]: ...
    async def list_analyses(self, goal_id: str = "") -> list[dict[str, Any]]: ...
